/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TesteXSpinner.java
 *
 * Created on 27/03/2010, 23:37:54
 */
package logisticequation.ui.components;

import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import logisticequation.ui.components.SliderSpinner.SpinnerPosition;
import logisticequation.ui.components.SliderSpinner.Orientation;

/**
 *
 * @author rafael
 */
public class TesteSliderSpinner extends javax.swing.JFrame {

    /** Creates new form TesteXSpinner */
    public TesteSliderSpinner() {
        initComponents();

        this.txfMaximo.setText(this.sliderSpinner.getMaximum().toString());
        this.txfMinimo.setText(this.sliderSpinner.getMinimum().toString());
        this.txfPadrao.setText(this.sliderSpinner.getPattern());
        this.txfPasso.setText(this.sliderSpinner.getStep().toString());
        this.txfPassoExtendido.setText(this.sliderSpinner.getExtendedStep().toString());
        this.txfValor.setText(this.sliderSpinner.getValue().toString());
        this.cmbSpinnerPosition.setSelectedItem(this.sliderSpinner.getSliderPosition());
        this.cmbOrientacao.setSelectedItem(this.sliderSpinner.getOrientation());
        this.txtTitulo.setText(this.sliderSpinner.getTitulo());

        this.lblMaximoReal.setText(this.sliderSpinner.getMaximum().toString());
        this.lblMinimoReal.setText(this.sliderSpinner.getMinimum().toString());
        this.lblPadraoReal.setText(this.sliderSpinner.getPattern());
        this.lblPassoReal.setText(this.sliderSpinner.getStep().toString());
        this.lblPassoExtREal.setText(this.sliderSpinner.getExtendedStep().toString());
        this.lblValorReal.setText(this.sliderSpinner.getValue().toString());
        this.lblOrientacaoREal.setText(this.sliderSpinner.getOrientation().name());
        this.lblSpinnerOrderReal.setText(this.sliderSpinner.getSliderPosition().name());
        this.lblTituloReal.setText(this.sliderSpinner.getTitulo());

        //this.txf.setText(this.spinner.get().toString());

        this.map.put(SliderSpinner.PROP_MAXIMUM, lblMaximoReal);
        this.map.put(SliderSpinner.PROP_MINIMUM, lblMinimoReal);
        this.map.put(SliderSpinner.PROP_ORDER, lblSpinnerOrderReal);
        this.map.put(SliderSpinner.PROP_SLIDER_POSITION, lblOrientacaoREal);
        this.map.put(SliderSpinner.PROP_PATTERN, lblPadraoReal);
        this.map.put(SliderSpinner.PROP_STEP, lblPassoReal);
        this.map.put(SliderSpinner.PROP_EXTENDED_STEP, lblPassoExtREal);
        this.map.put(SliderSpinner.PROP_VALUE, lblValorReal);
        this.map.put(SliderSpinner.PROP_TITULO, lblTituloReal);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlControle = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        txfValor = new javax.swing.JTextField();
        lblMinimo = new javax.swing.JLabel();
        txfMinimo = new javax.swing.JTextField();
        lblMaximo = new javax.swing.JLabel();
        txfMaximo = new javax.swing.JTextField();
        lblPasso = new javax.swing.JLabel();
        txfPasso = new javax.swing.JTextField();
        lblPassoExtendido = new javax.swing.JLabel();
        txfPassoExtendido = new javax.swing.JTextField();
        lblPadrao = new javax.swing.JLabel();
        txfPadrao = new javax.swing.JTextField();
        lblOrientacao = new javax.swing.JLabel();
        cmbOrientacao = new javax.swing.JComboBox();
        lblOrdem = new javax.swing.JLabel();
        cmbSpinnerPosition = new javax.swing.JComboBox();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        pnlValores = new javax.swing.JPanel();
        lblValor1 = new javax.swing.JLabel();
        lblMinimo1 = new javax.swing.JLabel();
        lblMaximo1 = new javax.swing.JLabel();
        lblPasso1 = new javax.swing.JLabel();
        lblPassoExtendido1 = new javax.swing.JLabel();
        lblPadrao1 = new javax.swing.JLabel();
        lblValorReal = new javax.swing.JLabel();
        lblPassoReal = new javax.swing.JLabel();
        lblMinimoReal = new javax.swing.JLabel();
        lblMaximoReal = new javax.swing.JLabel();
        lblPassoExtREal = new javax.swing.JLabel();
        lblPadraoReal = new javax.swing.JLabel();
        lblOrientacao1 = new javax.swing.JLabel();
        lblOrientacaoREal = new javax.swing.JLabel();
        lblOrdem1 = new javax.swing.JLabel();
        lblSpinnerOrderReal = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTituloReal = new javax.swing.JLabel();
        pnlSpinner = new javax.swing.JPanel();
        sliderSpinner = new logisticequation.ui.components.SliderSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teste de Configuração de XSPinner");

        pnlControle.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));
        pnlControle.setLayout(new java.awt.GridBagLayout());

        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblValor.setLabelFor(txfValor);
        lblValor.setText("Valor ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(lblValor, gridBagConstraints);

        txfValor.setColumns(6);
        txfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfValorActionPerformed(evt);
            }
        });
        txfValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfValorFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(txfValor, gridBagConstraints);

        lblMinimo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMinimo.setLabelFor(txfMinimo);
        lblMinimo.setText("Mínimo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(lblMinimo, gridBagConstraints);

        txfMinimo.setColumns(6);
        txfMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfMinimoActionPerformed(evt);
            }
        });
        txfMinimo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfMinimoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(txfMinimo, gridBagConstraints);

        lblMaximo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMaximo.setLabelFor(txfMaximo);
        lblMaximo.setText("Máximo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(lblMaximo, gridBagConstraints);

        txfMaximo.setColumns(6);
        txfMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfMaximoActionPerformed(evt);
            }
        });
        txfMaximo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfMaximoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(txfMaximo, gridBagConstraints);

        lblPasso.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPasso.setLabelFor(txfPasso);
        lblPasso.setText("Passo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(lblPasso, gridBagConstraints);

        txfPasso.setColumns(6);
        txfPasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPassoActionPerformed(evt);
            }
        });
        txfPasso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfPassoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(txfPasso, gridBagConstraints);

        lblPassoExtendido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassoExtendido.setLabelFor(txfPassoExtendido);
        lblPassoExtendido.setText("Pass. Ext.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(lblPassoExtendido, gridBagConstraints);

        txfPassoExtendido.setColumns(6);
        txfPassoExtendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPassoExtendidoActionPerformed(evt);
            }
        });
        txfPassoExtendido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfPassoExtendidoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(txfPassoExtendido, gridBagConstraints);

        lblPadrao.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPadrao.setLabelFor(txfPadrao);
        lblPadrao.setText("Padrão");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(lblPadrao, gridBagConstraints);

        txfPadrao.setColumns(6);
        txfPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPadraoActionPerformed(evt);
            }
        });
        txfPadrao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfPadraoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(txfPadrao, gridBagConstraints);

        lblOrientacao.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOrientacao.setLabelFor(cmbOrientacao);
        lblOrientacao.setText("Orientação");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(lblOrientacao, gridBagConstraints);

        cmbOrientacao.setModel(new DefaultComboBoxModel(new SliderSpinner.Orientation[]{SliderSpinner.Orientation.HORIZONTAL, SliderSpinner.Orientation.VERTICAL}));
        cmbOrientacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrientacaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(cmbOrientacao, gridBagConstraints);

        lblOrdem.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOrdem.setLabelFor(cmbSpinnerPosition);
        lblOrdem.setText("Ordem");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(lblOrdem, gridBagConstraints);

        cmbSpinnerPosition.setModel(new DefaultComboBoxModel(new SliderSpinner.SpinnerPosition[] {SliderSpinner.SpinnerPosition.BEGIN, SliderSpinner.SpinnerPosition.END}));
        cmbSpinnerPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSpinnerPositionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(cmbSpinnerPosition, gridBagConstraints);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTitulo.setLabelFor(txtTitulo);
        lblTitulo.setText("Título");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(lblTitulo, gridBagConstraints);

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlControle.add(txtTitulo, gridBagConstraints);

        getContentPane().add(pnlControle, java.awt.BorderLayout.NORTH);

        pnlValores.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));
        pnlValores.setLayout(new java.awt.GridBagLayout());

        lblValor1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblValor1.setLabelFor(lblValorReal);
        lblValor1.setText("Valor ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblValor1, gridBagConstraints);

        lblMinimo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMinimo1.setLabelFor(lblMinimoReal);
        lblMinimo1.setText("Mínimo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblMinimo1, gridBagConstraints);

        lblMaximo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMaximo1.setLabelFor(lblMaximoReal);
        lblMaximo1.setText("Máximo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblMaximo1, gridBagConstraints);

        lblPasso1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPasso1.setLabelFor(lblPadraoReal);
        lblPasso1.setText("Passo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblPasso1, gridBagConstraints);

        lblPassoExtendido1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassoExtendido1.setLabelFor(lblPassoExtREal);
        lblPassoExtendido1.setText("Pass. Ext.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblPassoExtendido1, gridBagConstraints);

        lblPadrao1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPadrao1.setLabelFor(lblPadraoReal);
        lblPadrao1.setText("Padrão");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblPadrao1, gridBagConstraints);

        lblValorReal.setPreferredSize(new java.awt.Dimension(28, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblValorReal, gridBagConstraints);

        lblPassoReal.setPreferredSize(new java.awt.Dimension(28, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblPassoReal, gridBagConstraints);

        lblMinimoReal.setPreferredSize(new java.awt.Dimension(28, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblMinimoReal, gridBagConstraints);

        lblMaximoReal.setPreferredSize(new java.awt.Dimension(28, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblMaximoReal, gridBagConstraints);

        lblPassoExtREal.setPreferredSize(new java.awt.Dimension(28, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblPassoExtREal, gridBagConstraints);

        lblPadraoReal.setPreferredSize(new java.awt.Dimension(28, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblPadraoReal, gridBagConstraints);

        lblOrientacao1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOrientacao1.setLabelFor(lblOrientacaoREal);
        lblOrientacao1.setText("Orientação");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblOrientacao1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblOrientacaoREal, gridBagConstraints);

        lblOrdem1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOrdem1.setLabelFor(lblSpinnerOrderReal);
        lblOrdem1.setText("Ordem");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblOrdem1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblSpinnerOrderReal, gridBagConstraints);

        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTitulo1.setLabelFor(lblTituloReal);
        lblTitulo1.setText("Título");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblTitulo1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlValores.add(lblTituloReal, gridBagConstraints);

        getContentPane().add(pnlValores, java.awt.BorderLayout.SOUTH);

        pnlSpinner.setFont(new java.awt.Font("Tahoma", 0, 18));

        sliderSpinner.setExtendedStep(50);
        sliderSpinner.setMaximum(1000);
        sliderSpinner.setPattern("0000");
        sliderSpinner.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sliderSpinnerPropertyChange(evt);
            }
        });
        pnlSpinner.add(sliderSpinner);

        getContentPane().add(pnlSpinner, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfPassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPassoActionPerformed
        mudarPasso();
    }//GEN-LAST:event_txfPassoActionPerformed

    private void txfMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfMinimoActionPerformed
        this.sliderSpinner.setMinimum(this.numberFromField(txfMinimo));
    }//GEN-LAST:event_txfMinimoActionPerformed

    private void txfMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfMaximoActionPerformed
        this.sliderSpinner.setMaximum(this.numberFromField(txfMaximo));
    }//GEN-LAST:event_txfMaximoActionPerformed

    private void txfPassoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfPassoFocusLost
        mudarPasso();
    }//GEN-LAST:event_txfPassoFocusLost

    private void txfMinimoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfMinimoFocusLost
        this.sliderSpinner.setMinimum(this.numberFromField(txfMinimo));
    }//GEN-LAST:event_txfMinimoFocusLost

    private void txfMaximoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfMaximoFocusLost
        this.sliderSpinner.setMaximum(this.numberFromField(txfMaximo));
    }//GEN-LAST:event_txfMaximoFocusLost

    private void txfPassoExtendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPassoExtendidoActionPerformed
        this.sliderSpinner.setExtendedStep(this.numberFromField(txfPassoExtendido));
    }//GEN-LAST:event_txfPassoExtendidoActionPerformed

    private void txfPassoExtendidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfPassoExtendidoFocusLost
        this.sliderSpinner.setExtendedStep(this.numberFromField(txfPassoExtendido));
    }//GEN-LAST:event_txfPassoExtendidoFocusLost

    private void txfPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPadraoActionPerformed
        this.sliderSpinner.setPattern(txfPadrao.getText());
    }//GEN-LAST:event_txfPadraoActionPerformed

    private void txfPadraoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfPadraoFocusLost
        this.sliderSpinner.setPattern(txfPadrao.getText());
    }//GEN-LAST:event_txfPadraoFocusLost

    private void txfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfValorActionPerformed
        mudarValor();
    }//GEN-LAST:event_txfValorActionPerformed

    private void txfValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfValorFocusLost
        mudarValor();
    }//GEN-LAST:event_txfValorFocusLost

    private void cmbOrientacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrientacaoActionPerformed
        this.sliderSpinner.setOrientation((Orientation) this.cmbOrientacao.getSelectedItem());
    }//GEN-LAST:event_cmbOrientacaoActionPerformed

    private void sliderSpinnerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sliderSpinnerPropertyChange
        JLabel label = this.map.get(evt.getPropertyName());

        if (label != null) {
            label.setText(evt.getNewValue().toString());
            if (evt.getPropertyName().equals(SliderSpinner.PROP_VALUE)) {
                this.txfValor.setText(evt.getNewValue().toString());
            }
        }
    }//GEN-LAST:event_sliderSpinnerPropertyChange

    private void cmbSpinnerPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSpinnerPositionActionPerformed
        this.sliderSpinner.setSliderPosition((SpinnerPosition) this.cmbSpinnerPosition.getSelectedItem());
    }//GEN-LAST:event_cmbSpinnerPositionActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        this.sliderSpinner.setTitulo(this.txtTitulo.getText());
    }//GEN-LAST:event_txtTituloActionPerformed

    private void mudarValor() {
        Number value = this.numberFromField(txfValor);
        if (value != null) {
            this.sliderSpinner.setValue(value);
        } else if (this.sliderSpinner.getValue() != null) {
            txfValor.setText(this.sliderSpinner.getValue().toString());
        }
    }

    private void mudarPasso() {
        Number value = this.numberFromField(txfPasso);
        if (value != null) {
            this.sliderSpinner.setStep(value);
        } else if (this.sliderSpinner.getStep() != null) {
            this.txfPasso.setText(this.sliderSpinner.getStep().toString());
        }
    }

    private Number numberFromField(JTextField textField) {
        String text = textField.getText();
        if (text.matches(intPattern)) {
            return Integer.valueOf(text);
        }
        if (text.matches(doublePattern)) {
            return Double.valueOf(text);
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TesteSliderSpinner().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbOrientacao;
    private javax.swing.JComboBox cmbSpinnerPosition;
    private javax.swing.JLabel lblMaximo;
    private javax.swing.JLabel lblMaximo1;
    private javax.swing.JLabel lblMaximoReal;
    private javax.swing.JLabel lblMinimo;
    private javax.swing.JLabel lblMinimo1;
    private javax.swing.JLabel lblMinimoReal;
    private javax.swing.JLabel lblOrdem;
    private javax.swing.JLabel lblOrdem1;
    private javax.swing.JLabel lblOrientacao;
    private javax.swing.JLabel lblOrientacao1;
    private javax.swing.JLabel lblOrientacaoREal;
    private javax.swing.JLabel lblPadrao;
    private javax.swing.JLabel lblPadrao1;
    private javax.swing.JLabel lblPadraoReal;
    private javax.swing.JLabel lblPasso;
    private javax.swing.JLabel lblPasso1;
    private javax.swing.JLabel lblPassoExtREal;
    private javax.swing.JLabel lblPassoExtendido;
    private javax.swing.JLabel lblPassoExtendido1;
    private javax.swing.JLabel lblPassoReal;
    private javax.swing.JLabel lblSpinnerOrderReal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTituloReal;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValorReal;
    private javax.swing.JPanel pnlControle;
    private javax.swing.JPanel pnlSpinner;
    private javax.swing.JPanel pnlValores;
    private logisticequation.ui.components.SliderSpinner sliderSpinner;
    private javax.swing.JTextField txfMaximo;
    private javax.swing.JTextField txfMinimo;
    private javax.swing.JTextField txfPadrao;
    private javax.swing.JTextField txfPasso;
    private javax.swing.JTextField txfPassoExtendido;
    private javax.swing.JTextField txfValor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
    private String intPattern = "^[+-]?\\d+$";
    private String doublePattern = "^[+-]?\\d+(,|\\.)?\\d*$";
    private Map<String, JLabel> map = new HashMap<String, JLabel>();
}
