package logisticequation.ui;

import java.awt.Color;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author rafael
 */
public class Logistic1 extends javax.swing.JFrame implements ChangeListener {

    /** Creates new form Logistic1 */
    public Logistic1() {
        initComponents();

        slspK.addChangeListener(this);
        slspX0.addChangeListener(this);
        slspIteracoes.addChangeListener(this);
        slspIgnorados.addChangeListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graph = new logisticequation.ui.JXGraph1();
        slspK = new logisticequation.ui.components.SliderSpinner();
        pnlX0Iteracoes = new javax.swing.JPanel();
        slspX0 = new logisticequation.ui.components.SliderSpinner();
        slspIteracoes = new logisticequation.ui.components.SliderSpinner();
        jPanel1 = new javax.swing.JPanel();
        chbRastro = new javax.swing.JCheckBox();
        slspIgnorados = new logisticequation.ui.components.SliderSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equação Logistica");
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        graph.setFocusable(false);
        graph.setInputEnabled(false);
        graph.setMajorX(0.1);
        graph.setMajorY(0.1);
        graph.setMinorCountX(5);
        graph.setMinorCountY(5);
        graph.setView(new java.awt.geom.Rectangle2D.Double(-0.0, -0.1, 1.0, 1.1));
        graph.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                graphComponentResized(evt);
            }
        });

        org.jdesktop.layout.GroupLayout graphLayout = new org.jdesktop.layout.GroupLayout(graph);
        graph.setLayout(graphLayout);
        graphLayout.setHorizontalGroup(
            graphLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 421, Short.MAX_VALUE)
        );
        graphLayout.setVerticalGroup(
            graphLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 257, Short.MAX_VALUE)
        );

        getContentPane().add(graph, java.awt.BorderLayout.CENTER);
        graph.addPlots(Color.GREEN, this.parabolaPlot);
        graph.addPlots(Color.LIGHT_GRAY, new LinePlot());

        slspK.setExtendedStep(0.100);
        slspK.setIntervals(4000);
        slspK.setMaximum(4.00);
        slspK.setMinimum(0.00);
        slspK.setOrientation(logisticequation.ui.components.SliderSpinner.Orientation.VERTICAL);
        slspK.setPattern("0.000");
        slspK.setStep(0.001);
        slspK.setTitulo("K");
        slspK.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                slspKPropertyChange(evt);
            }
        });
        getContentPane().add(slspK, java.awt.BorderLayout.EAST);

        pnlX0Iteracoes.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        slspX0.setExtendedStep(0.10);
        slspX0.setMaximum(1.00);
        slspX0.setMinimum(0.00);
        slspX0.setPattern("0.00");
        slspX0.setStep(0.01);
        slspX0.setTitulo("X0");
        pnlX0Iteracoes.add(slspX0);

        slspIteracoes.setExtendedStep(10);
        slspIteracoes.setIntervals(2000);
        slspIteracoes.setMaximum(2000);
        slspIteracoes.setPattern("0000");
        slspIteracoes.setTitulo("Iterações");
        pnlX0Iteracoes.add(slspIteracoes);

        jPanel1.setLayout(new java.awt.BorderLayout(5, 5));

        chbRastro.setMnemonic('E');
        chbRastro.setText("Exibir Rastro");
        chbRastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbRastroActionPerformed(evt);
            }
        });
        jPanel1.add(chbRastro, java.awt.BorderLayout.WEST);

        slspIgnorados.setExtendedStep(10);
        slspIgnorados.setMaximum(100);
        slspIgnorados.setMinimum(0);
        slspIgnorados.setPattern(" 00");
        slspIgnorados.setTitulo("Porcentagem das iterações a serem ignoradas");
        slspIgnorados.setValue(0);
        jPanel1.add(slspIgnorados, java.awt.BorderLayout.CENTER);

        pnlX0Iteracoes.add(jPanel1);

        getContentPane().add(pnlX0Iteracoes, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slspKPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_slspKPropertyChange
        this.changeK();
    }//GEN-LAST:event_slspKPropertyChange

    private void graphComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_graphComponentResized
        this.repaintGraph();
    }//GEN-LAST:event_graphComponentResized

    private void chbRastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbRastroActionPerformed
        this.repaintGraph();
    }//GEN-LAST:event_chbRastroActionPerformed

    private void changeK() {
        this.parabolaPlot.setK((Double) this.slspK.getValue());
        this.repaintGraph();
    }

    public void stateChanged(ChangeEvent e) {
        this.repaintGraph();
    }

    private void repaintGraph() {
        this.graph.setParameters((Double) this.slspX0.getValue(), (Double) this.slspK.getValue(), (Integer) this.slspIteracoes.getValue(), this.chbRastro.isSelected(), (Integer) this.slspIgnorados.getValue());
        this.graph.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Logistic1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbRastro;
    private logisticequation.ui.JXGraph1 graph;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlX0Iteracoes;
    private logisticequation.ui.components.SliderSpinner slspIgnorados;
    private logisticequation.ui.components.SliderSpinner slspIteracoes;
    private logisticequation.ui.components.SliderSpinner slspK;
    private logisticequation.ui.components.SliderSpinner slspX0;
    // End of variables declaration//GEN-END:variables
    private LogisticPlot parabolaPlot = new LogisticPlot();
}
