package logisticequation.ui.components;

import java.awt.event.KeyListener;
import java.awt.event.MouseWheelListener;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;

/**
 *
 * @author rafael
 */
public class JXSpinner extends JSpinner implements Serializable {

    public static final String PROP_EXTENDED_STEP = "extendedStep";
    public static final String PROP_MAXIMUM = "maximum";
    public static final String PROP_MINIMUM = "minimum";
    public static final String PROP_PATTERN = "pattern";
    public static final String PROP_STEP = "step";
    public static final String PROP_VALUE = "value";
    private Number step = 1;
    private Number extendedStep = 1;
    private Number minimum = 0;
    private Number maximum = 10;
    private String pattern = "00";

    /** Creates new form BeanForm */
    public JXSpinner() {
        super();
        initComponents();
        initModel();
    }

    public JXSpinner(SpinnerModel model) {
        super(model);
        initComponents();
        initModel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setModel(new XSpinnerNumberModel.IntXSpinnerNumberModel());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void initModel() {
        this.getModelAsXModel().setExtendedStep(extendedStep);
        this.getModelAsXModel().setStepSize(step);
        this.getModelAsXModel().setMaximum(maximum);
        this.getModelAsXModel().setMinimum(minimum);
    }

    private XSpinnerNumberModel alterarModel(Number newStep) {
        XSpinnerNumberModel newModel = null;

        if (newStep instanceof Integer) {
            newModel = new XSpinnerNumberModel.IntXSpinnerNumberModel();
            newModel.setExtendedStep(this.getModelAsXModel().getExtendedStep().intValue());
            newModel.setMaximum((Comparable) (((Number) this.getModelAsXModel().getMaximum()).intValue()));
            newModel.setMinimum((Comparable) (((Number) this.getModelAsXModel().getMinimum()).intValue()));
            newModel.setValue(((Number) this.getModelAsXModel().getMinimum()).intValue());
        } else if (newStep instanceof Double) {
            newModel = new XSpinnerNumberModel.DoubleXSpinnerNumberModel();
            newModel.setExtendedStep(this.getModelAsXModel().getExtendedStep().doubleValue());
            newModel.setMaximum((Comparable) (((Number) this.getModelAsXModel().getMaximum()).doubleValue()));
            newModel.setMinimum((Comparable) (((Number) this.getModelAsXModel().getMinimum()).doubleValue()));
            newModel.setValue(((Number) this.getModelAsXModel().getMinimum()).doubleValue());
        } else if (newStep instanceof BigDecimal) {
            newModel = new XSpinnerNumberModel.BigDecimalXSpinnerNumberModel();
            newModel.setExtendedStep(new BigDecimal(this.getModelAsXModel().getExtendedStep().doubleValue()));
            newModel.setMaximum((Comparable) (new BigDecimal(((Number) this.getModelAsXModel().getMaximum()).doubleValue())));
            newModel.setMinimum((Comparable) (new BigDecimal(((Number) this.getModelAsXModel().getMinimum()).doubleValue())));
            newModel.setValue(new BigDecimal(((Number) this.getModelAsXModel().getMinimum()).doubleValue()));
        } else {
            throw new IllegalArgumentException("Tipo sem NumberModel adequado:" + newStep.getClass().getName());
        }
        newModel.setStepSize(newStep);

        this.extendedStep = newModel.getExtendedStep();
        this.maximum = (Number) newModel.getMaximum();
        this.minimum = (Number) newModel.getMinimum();
        this.setValue(newModel.getValue());

        return newModel;
    }

    private void tratarNovoXEditor(XNumberEditor editor) {
        for (MouseWheelListener l : super.getMouseWheelListeners()) {
            if (l instanceof XNumberEditor) {
                super.removeMouseWheelListener(l);
            }
        }
        super.addMouseWheelListener(editor);

        JComponent textField = editor.getTextField();
        for (KeyListener l : textField.getKeyListeners()) {
            if (l instanceof XNumberEditor) {
                textField.removeKeyListener(l);
            }
        }
        textField.addKeyListener(editor);
    }

    private XNumberEditor createNewEditor(String pattern) {
        XNumberEditor editor = new XNumberEditor(this, (pattern != null) ? pattern : "");
        tratarNovoXEditor(editor);
        return editor;
    }

    private XSpinnerNumberModel getModelAsXModel() {
        return (XSpinnerNumberModel) super.getModel();
    }

    private XNumberEditor getEditorAsXEditor() {
        return (XNumberEditor) super.getEditor();
    }

    private void notificarAlteracao(String propertyName, Object oldValue, Object newValue) {
        boolean valorAlterado = ((oldValue == null) && (newValue != null))
                || ((oldValue != null) && (newValue == null))
                || ((oldValue != null) && (newValue != null) && !oldValue.equals(newValue));
        if(valorAlterado) {
            super.firePropertyChange(propertyName, oldValue, newValue);
        }
    }

    @Override
    protected JComponent createEditor(SpinnerModel model) {
        return createNewEditor(this.getPattern());
    }

    @Override
    public void setValue(Object value) {
        Number oldValue = (Number) super.getValue();
        super.setValue((Number)value);
        this.notificarAlteracao(PROP_VALUE, oldValue, value);
    }

    public Number getExtendedStep() {
        return extendedStep;
    }

    public void setExtendedStep(Number extendedStep) {
        Number oldValue = this.extendedStep;
        this.extendedStep = extendedStep;
        this.getModelAsXModel().setExtendedStep(this.extendedStep);
        this.notificarAlteracao(PROP_EXTENDED_STEP, oldValue, this.extendedStep);
    }

    public Number getMaximum() {
        return maximum;
    }

    public void setMaximum(Number maximum) {
        Number oldValue = this.maximum;
        this.maximum = maximum;
        this.getModelAsXModel().setMaximum(this.maximum);
        this.notificarAlteracao(PROP_MAXIMUM, oldValue, this.maximum);
    }

    public Number getMinimum() {
        return minimum;
    }

    public void setMinimum(Number minimum) {
        Number oldValue = this.minimum;
        this.minimum = minimum;
        this.getModelAsXModel().setMinimum(this.minimum);
        this.notificarAlteracao(PROP_MINIMUM, oldValue, this.minimum);
    }

    @Override
    public void setEditor(JComponent editor) {
        final XNumberEditor xEditor = (XNumberEditor) editor;
        this.tratarNovoXEditor(xEditor);
        super.setEditor(xEditor);
    }

    @Override
    public void setModel(SpinnerModel model) {
        super.setModel((XSpinnerNumberModel) model);
    }

    public String getPattern() {
        return pattern;
    }

    public void setPattern(String pattern) {
        String oldValue = this.pattern;
        this.pattern = pattern;
        super.setEditor(this.createNewEditor(pattern));
        this.notificarAlteracao(PROP_PATTERN, oldValue, this.pattern);
    }

    public Number getStep() {
        return step;
    }

    public void setStep(Number step) {
        Number oldValue = this.step;
        this.step = step;

        if (this.step.getClass() == oldValue.getClass()) {
            this.getModelAsXModel().setStepSize(step);
            this.notificarAlteracao(PROP_STEP, oldValue, this.step);
        } else {
            this.notificarAlteracao(PROP_STEP, oldValue, this.step);
            this.setModel(this.alterarModel(step));
        }
    }
}
